name:                ivy
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/ivy#readme
license:             BSD3
author:              Rohit Ramesh
maintainer:          rkr@berkeley.edu
copyright:           2019 Rohit Ramesh
#category:
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - intro
  - tasty
  - tasty-discover
  - tasty-hunit
  - tasty-hedgehog
  - hedgehog
  - free
  - recursion-schemes
  - data-reify

library:
  source-dirs: src
  exposed-modules:
    - Ivy.Prelude
    - Ivy.Scratchpad

tests:
  tasty:
    main: TastyDriver.hs
    source-dirs:
      - test
      - src

default-extensions:
  NoImplicitPrelude
  ApplicativeDo
  BangPatterns
  ConstraintKinds
  DataKinds
  DefaultSignatures
  DeriveDataTypeable
  DeriveFoldable
  DeriveFunctor
  DeriveGeneric
  DeriveLift
  DeriveTraversable
  DerivingStrategies
  DuplicateRecordFields
  EmptyCase
  EmptyDataDecls
  ExistentialQuantification
  ExtendedDefaultRules
  FlexibleContexts
  FlexibleInstances
  FunctionalDependencies
  GADTs
  GeneralizedNewtypeDeriving
  ImplicitParams
  InstanceSigs
  KindSignatures
  LambdaCase
  MultiParamTypeClasses
  MultiWayIf
  NamedFieldPuns
  NoImplicitPrelude
  NoMonomorphismRestriction
  OverloadedLabels
  OverloadedLists
  OverloadedStrings
  PackageImports
  PatternSynonyms
  PolyKinds
  QuasiQuotes
  QuantifiedConstraints
  RankNTypes
  RecordWildCards
  RecursiveDo
  ScopedTypeVariables
  StandaloneDeriving
  TemplateHaskell
  TupleSections
  TypeApplications
  TypeFamilies
  TypeFamilyDependencies
  TypeOperators
  ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Werror
  - -Wsemigroup
  # Some of the flags enabled by Wall and propmoted by Werror really should
  # only be warnings when developing. A proper build on the other hand should
  # have no warnings attached
  - -Wwarn=redundant-constraints
  - -Wwarn=unused-matches
  - -Wwarn=deprecations
  - -Wwarn=unused-local-binds # TODO :: Re-enable when you feel like cleaning
  - -Wwarn=unused-imports # TODO :: Re-enable when you feel like cleaning
  # - -fno-warn-orphans
  # - -fno-warn-type-defaults
  # - -fno-warn-name-shadowing
  # - -fno-warn-unticked-promoted-constructors
                             #         up your imports.
  # - -fprint-potential-instances
  - -ddump-cs-trace
  - -ddump-splices
  - -ddump-to-file
  - -fprint-typechecker-elaboration
  #- -prof
